import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import "./font.css";
import Navbar from "@/interface/components/Navbar";

import Test from "@/interface/components/Test";

// Poppins doesn't support Thai language use Kanit instead
const kanit = Kanit({
  weight: ['300','400', '500', '600', '700'],
  subsets: ["latin", "thai"],
  variable: "--font-kanit",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={kanit.className}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
